package interpreter;

public enum Simboli {
    NEW, DEL, MV, MVOFF, SCALE, LS, ALL, GROUPS, GRP, UNGRP, AREA, PERIMETER,
    TONDA_APERTA, TONDA_CHIUSA, VIRGOLA, CHAR_INVALIDO, EOE, NUMERO_O_STRINGA,CIRCLE, RECTANGLE, IMAGE
}

